
version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: cimg/rust:1.54-node
        auth:
          username: jasperrlz
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
      - run: sudo apt-get update && sudo apt-get install rsync

      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run: yarn install

      # https://andelf.github.io/blog/2016/11/18/circleci-meets-rust/
      # https://github.com/rust-lang/cargo/issues/2078
      - run: sed -i 's/github/git-non-exist-hub/g' ~/.gitconfig

      # wasm-pack is amazingly ridiculous and puts a binary in .config/, which
      # won't get cached even when node_modules does. Force it to reinstall with
      # an 'upgrade'.
      - run: yarn upgrade wasm-pack

      - run:
          command: yarn run build
          environment:
            CARGO_TERM_VERBOSE: true

      - save_cache:
          paths:
            - node_modules
            - .cache
          key: v3-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys:
          fingerprints:
            - "4f:78:69:e1:6b:2d:bf:39:96:c5:4a:1c:d1:90:40:6e"

      - deploy:
          name: deploy
          command: |
            echo 'foxcraft.dreamhost.com,173.236.176.143 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjDUVvhTtiSo7nczLMlOaTk/fQ7dcmDTLNIzGy4QAg/PhFp3b4AGuS7qyjEZV31Wt0nwN0lC7X3CnsIxY5bBCFJ+ATwwLwxG3bcZKf4IJMP1coDcIxTRAQ9CeLsPmiNGDURLCX33ZI/+ZSxEOi4Ir0sqCE11CElKivVebeRBQiIpEWvW5ZoD4j52uksjDxwsjRKp+CDCHBhVMmJ9DjnPBTCach1zi9AkVeSpa6yh/chKPutHjqx4Xli/w8mXsQcS7Y79H0YMCAk7Y3xknKPO+QTXR7P+KKTx4eyKxHFXEd0fp1VE5JOdLB/SsZS+VWXeusVRcM2oDnSlyi5pEimUjf' >> ~/.ssh/known_hosts
            rsync -va --delete-after --exclude=data/ --exclude=priv/ --exclude=.well-known/ dist/ gznoclip@foxcraft.dreamhost.com:noclip.website/
