
version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: cimg/rust:1.77.1-node
        auth:
          username: jasperrlz
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
      - run: sudo apt-get update && sudo apt-get install rsync

      - checkout

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "package.json" }}-{{ checksum rust/Cargo.toml }}

      - run: sudo npm install -g pnpm

      - run: pnpm install

      - run: pnpm run build

      - save_cache:
          paths:
            - node_modules
            - .cache
            - .cargo
          key: v4-dependencies-{{ checksum "package.json" }}-{{ checksum rust/Cargo.toml }}

      - add_ssh_keys:
          fingerprints:
            - "4f:78:69:e1:6b:2d:bf:39:96:c5:4a:1c:d1:90:40:6e"

      - run:
          name: deploy
          command: |
            echo 'iad1-shared-e1-29.dreamhost.com,173.236.136.139 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPWamoZmDg7rwutGWQSxvdjAW9QyAOL2Q6JDYmrO09kEPh7+FYyOm7AiEK8mn/mUxL8dPPOifzv2zy90BjEERAo=' >> ~/.ssh/known_hosts
            rsync -va --delete-after --exclude=data/ --exclude=priv/ --exclude=.well-known/ dist/ gznoclip@iad1-shared-e1-29.dreamhost.com:noclip.website/
